name: Sync Spotify to YT Music
on:
  schedule:
    - cron: '0 * * * *' # Gira ogni notte alle 02:00
  workflow_dispatch: # Ti permette di avviarlo a mano quando vuoi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install spotify-to-ytmusic

      - name: Run sync
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          YT_COOKIE: ${{ secrets.YT_COOKIE }}
        run: |
          # Usiamo 'python -m' per essere sicuri che GitHub trovi lo script
          python -m spotify_to_ytmusic setup --no-auth
          python -m spotify_to_ytmusic sync all
