name: Sync Spotify to YT Music
on:
  schedule:
    - cron: '0 * * * *' # Gira ogni notte alle 02:00
  workflow_dispatch: # Ti permette di avviarlo a mano quando vuoi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install spotify-to-ytmusic

      - name: Run sync
        run: |
          # 1. Creiamo il file nella cartella corrente (dove abbiamo i permessi)
          cat <<EOF > my_settings.ini
          [spotify]
          client_id = ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret = ${{ secrets.SPOTIFY_CLIENT_SECRET }}

          [youtube]
          headers_raw = ${{ secrets.YT_COOKIE }}
          EOF
          
          # 2. Esportiamo il percorso del file così lo script lo trova subito
          export SPOTIFY_TO_YT_CONFIG=$(pwd)/my_settings.ini
          export PATH=$PATH:/home/runner/.local/bin

          # 3. Lanciamo il comando
          spotify_to_ytmusic all me
